# Generated by Django 5.2.4 on 2025-08-10 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_count", models.PositiveIntegerField()),
                ("study_time_minutes", models.PositiveIntegerField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="assignment__user_id_060217_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="assignment__timesta_b59131_idx"
                    ),
                ],
                "unique_together": {("user", "timestamp")},
            },
        ),
    ]
